### ISSUE TITLE
Issue using GPUID =1, unable to make predictions

### ISSUE THREAD

**Issue by YaYaB** [beniz/deepdetect#299]
I have an issue trying to do predictions with a GPU that has the id 1.

#### Configuration
- Version of DeepDetect:
    - Locally compiled on Ubuntu 16.04 LTS
- Commit (shown by the server when starting):
    - Branch `Master`, 24f40b6993dedbedd223ced45f3b88dd0762da63
- GPUS:
    - 2 x Nvidia GTX Titan X (Maxwell)

#### Your question / the problem you're facing:
When I try to make the prediction using your library dd_client, the results differ if I use GPU0 or GPU1. The issue appears when trying to make a prediction using the GPU with the id 1. For your information, I use a pretrained GoogleNet model.
Below you will find the output of `nvidia-smi`.
```
Thu Apr 27 09:15:48 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:02:00.0     Off |                  N/A |
| 22%   40C    P8    14W / 250W |    170MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:05:00.0      On |                  N/A |
| 22%   36C    P8    14W / 250W |     57MiB / 12204MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```

First I launch DeepDetect
INPUT
```
INPUT
./dede --port 8085
```
OUTPUT
```
DeepDetect [ commit 24f40b6993dedbedd223ced45f3b88dd0762da63 ]
INFO - 09:09:28 - Running DeepDetect HTTP server on localhost:8085
```

Second, I create the service, as you can see I use `gpuid:0`. 
Please note that the folder `test_gpu` only contains `googlenet.caffemodel` before creating the service.
INPUT
```
    dd = DD('localhost', port=8085)
    dd.set_return_format(dd.RETURN_PYTHON)
    description = 'Prediction service'
    mllib = 'caffe'
    type_ = 'unsupervised'
    model = {'templates': '/home/templates/', 'repository': '/home/test_gpu'}
    parameters_input = {'connector':'image',  'width':224, 'height':224}
    parameters_mllib = {'template':'googlenet', 'nclasses':1000, 'gpu':True, 'gpuid':[0, 1]}
    parameters_output = {}
    dd.put_service('pred_serv', model=model, description=description, mllib=mllib, mltype=type_, parameters_input=parameters_input, parameters_mllib=parameters_mllib, parameters_output=parameters_output)

{'status': {'code': 201, 'msg': 'Created'}}
```

OUTPUT
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0427 09:15:19.108695  2568 caffelib.cc:103] Using GPU 0

INFO - 09:15:19 - Device id:                     0
INFO - 09:15:19 - Major revision number:         5
INFO - 09:15:19 - Minor revision number:         2
INFO - 09:15:19 - Name:                          GeForce GTX TITAN X
INFO - 09:15:19 - Total global memory:           12800163840
INFO - 09:15:19 - Total shared memory per block: 49152
INFO - 09:15:19 - Total registers per block:     65536
INFO - 09:15:19 - Warp size:                     32
INFO - 09:15:19 - Maximum memory pitch:          2147483647
INFO - 09:15:19 - Maximum threads per block:     1024
INFO - 09:15:19 - Maximum dimension of block:    1024, 1024, 64
INFO - 09:15:19 - Maximum dimension of grid:     2147483647, 65535, 65535
INFO - 09:15:19 - Clock rate:                    1076000
INFO - 09:15:19 - Total constant memory:         65536
INFO - 09:15:19 - Texture alignment:             512
INFO - 09:15:19 - Concurrent copy and execution: Yes
INFO - 09:15:19 - Number of multiprocessors:     24
I0427 09:15:19.800282  2568 caffelib.cc:130] instantiating model template googlenet
I0427 09:15:19.800310  2568 caffelib.cc:134] source=/home/templates//googlenet/
I0427 09:15:19.800314  2568 caffelib.cc:135] dest=/home/test_gpu/googlenet.prototxt
INFO - 09:15:19 - Kernel execution timeout:      No
INFO - 09:15:19 - Thu Apr 27 09:15:19 2017 UTC - 127.0.0.1 "PUT /services/pred_serv" 201 698

```

Then I make a call to do some predictions.
INPUT
```
    # Create Prediction
    parameters_input = {'width':224, 'height':224}
    parameters_mllib = {'gpu':True, 'gpuid':0, 'extract_layer':'loss3/classifier', "net": {"test_batch_size": 1}}
    parameters_output = {}
    parameters_input = {}

    # TEST GPU
    predict_output = dd.post_predict('pred_serv', data, parameters_input, parameters_mllib, parameters_output)
```

OUTPUT
```
INFO - 09:16:38 - Initializing net from parameters: 
....
....
I0427 09:16:39.441259  2574 caffelib.cc:387] Using pre-trained weights from /home/test_gpu/googlenet.caffemodel
INFO - 09:16:39 - Network initialization done.
INFO - 09:16:39 - Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/test_gpu/googlenet.caffemodel
INFO - 09:16:39 - Successfully upgraded file specified using deprecated V1LayerParameter
INFO - 09:16:39 - Ignoring source layer data
INFO - 09:16:39 - Ignoring source layer label_data_1_split
INFO - 09:16:39 - Ignoring source layer loss1/ave_pool
INFO - 09:16:39 - Ignoring source layer loss1/conv
INFO - 09:16:39 - Ignoring source layer loss1/relu_conv
INFO - 09:16:39 - Ignoring source layer loss1/fc
INFO - 09:16:39 - Ignoring source layer loss1/relu_fc
INFO - 09:16:39 - Ignoring source layer loss1/drop_fc
INFO - 09:16:39 - Ignoring source layer loss1/classifier
INFO - 09:16:39 - Ignoring source layer loss1/loss
INFO - 09:16:39 - Ignoring source layer loss2/ave_pool
INFO - 09:16:39 - Ignoring source layer loss2/conv
INFO - 09:16:39 - Ignoring source layer loss2/relu_conv
INFO - 09:16:39 - Ignoring source layer loss2/fc
INFO - 09:16:39 - Ignoring source layer loss2/relu_fc
INFO - 09:16:39 - Ignoring source layer loss2/drop_fc
INFO - 09:16:39 - Ignoring source layer loss2/classifier
INFO - 09:16:39 - Ignoring source layer loss2/loss
INFO - 09:16:39 - Ignoring source layer pool5/drop_7x7_s1
I0427 09:16:39.682440  2574 caffelib.cc:1703] Net total flops=1582671872 / total params=6990272
I0427 09:16:39.682531  2574 caffelib.cc:103] Using GPU 0
INFO - 09:16:39 - Ignoring source layer loss3/loss3
INFO - 09:16:40 - Thu Apr 27 09:16:40 2017 UTC - 127.0.0.1 "POST /predict" pred_serv 200 1332

```

As you can see the predictions are returned.
INPUT
```
print( predict_output)
```

OUTPUT
```
{'body': {'predictions': [{'uri': '/mnt/kaidee/004/680/i1.24x7th.com_df_0_ui_post_2016_12_06_5_b_cc83a27f346483219fb44091d269a1c9.jpeg',
    'vals': [-0.5022280216217041,
     4.4008612632751465,
     ......
     ......
     1.0949723720550537,
     -3.4063827991485596,
     -1.7683202028274536,
     0.5700303912162781]}]},
 'head': {'method': '/predict', 'service': 'pred_serv', 'time': 1331.0},
 'status': {'code': 200, 'msg': **'OK'}}z**
```

Now if I do exactly the same and modify the `gpuid:1`, I get the following:
INPUT
```
    dd = DD('localhost', port=8085)
    dd.set_return_format(dd.RETURN_PYTHON)
    description = 'Prediction service'
    mllib = 'caffe'
    type_ = 'unsupervised'
    model = {'templates': '/home/yassine.bezza/templates/', 'repository': '/home/yassine.bezza/test_gpu'}
    parameters_input = {'connector':'image',  'width':224, 'height':224}
    parameters_mllib = {'template':'googlenet', 'nclasses':1000, 'gpu':True, 'gpuid':1}
    parameters_output = {}
    dd.put_service('pred_serv', model=model, description=description, mllib=mllib, mltype=type_, parameters_input=parameters_input, parameters_mllib=parameters_mllib, parameters_output=parameters_output)

{'status': {'code': 201, 'msg': 'Created'}}
```

OUTPUT
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0427 09:20:56.425547  2762 caffelib.cc:103] Using GPU 1

INFO - 09:20:57 - Device id:                     1
INFO - 09:20:57 - Major revision number:         5
INFO - 09:20:57 - Minor revision number:         2
INFO - 09:20:57 - Name:                          GeForce GTX TITAN X
INFO - 09:20:57 - Total global memory:           12796887040
INFO - 09:20:57 - Total shared memory per block: 49152
INFO - 09:20:57 - Total registers per block:     65536
INFO - 09:20:57 - Warp size:                     32
INFO - 09:20:57 - Maximum memory pitch:          2147483647
INFO - 09:20:57 - Maximum threads per block:     1024
INFO - 09:20:57 - Maximum dimension of block:    1024, 1024, 64
INFO - 09:20:57 - Maximum dimension of grid:     2147483647, 65535, 65535
INFO - 09:20:57 - Clock rate:                    1076000
INFO - 09:20:57 - Total constant memory:         65536
INFO - 09:20:57 - Texture alignment:             512
INFO - 09:20:57 - Concurrent copy and execution: Yes
INFO - 09:20:57 - Number of multiprocessors:     24
I0427 09:20:57.118757  2762 caffelib.cc:130] instantiating model template googlenet
I0427 09:20:57.118772  2762 caffelib.cc:134] source=/home/templates//googlenet/
I0427 09:20:57.118777  2762 caffelib.cc:135] dest=/home/test_gpu/googlenet.prototxt
INFO - 09:20:57 - Kernel execution timeout:      Yes
INFO - 09:20:57 - Thu Apr 27 09:20:57 2017 UTC - 127.0.0.1 "PUT /services/pred_serv" 201 699

```

Then I make a call to do some predictions.
INPUT
```
    # Create Prediction
    parameters_input = {'width':224, 'height':224}
    parameters_mllib = {'gpu':True, 'gpuid':1, 'extract_layer':'loss3/classifier', "net": {"test_batch_size": 1}}
    parameters_output = {}
    parameters_input = {}

    # TEST GPU
    predict_output = dd.post_predict('pred_serv', data, parameters_input, parameters_mllib, parameters_output)
```

OUTPUT
```
INFO - 09:22:41 - Initializing net from parameters: 

INFO - 09:22:41 - Creating layer / name=googlenet / type=MemoryData
INFO - 09:22:41 - Creating Layer googlenet
INFO - 09:22:41 - googlenet -> data
INFO - 09:22:41 - googlenet -> label
INFO - 09:22:41 - Setting up **googlenetz**
.......
.......
I0427 09:22:41.719919  2778 caffelib.cc:387] Using pre-trained weights from /home/test_gpu/googlenet.caffemodel
INFO - 09:22:41 - Network initialization done.
INFO - 09:22:41 - Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/test_gpu/googlenet.caffemodel
INFO - 09:22:41 - Successfully upgraded file specified using deprecated V1LayerParameter
INFO - 09:22:41 - Ignoring source layer data
INFO - 09:22:41 - Ignoring source layer label_data_1_split
INFO - 09:22:41 - Ignoring source layer loss1/ave_pool
INFO - 09:22:41 - Ignoring source layer loss1/conv
INFO - 09:22:41 - Ignoring source layer loss1/relu_conv
INFO - 09:22:41 - Ignoring source layer loss1/fc
INFO - 09:22:41 - Ignoring source layer loss1/relu_fc
INFO - 09:22:41 - Ignoring source layer loss1/drop_fc
INFO - 09:22:41 - Ignoring source layer loss1/classifier
INFO - 09:22:41 - Ignoring source layer loss1/loss
INFO - 09:22:41 - Ignoring source layer loss2/ave_pool
INFO - 09:22:41 - Ignoring source layer loss2/conv
INFO - 09:22:41 - Ignoring source layer loss2/relu_conv
INFO - 09:22:41 - Ignoring source layer loss2/fc
INFO - 09:22:41 - Ignoring source layer loss2/relu_fc
INFO - 09:22:41 - Ignoring source layer loss2/drop_fc
INFO - 09:22:41 - Ignoring source layer loss2/classifier
INFO - 09:22:41 - Ignoring source layer loss2/loss
INFO - 09:22:41 - Ignoring source layer pool5/drop_7x7_s1
I0427 09:22:41.974454  2778 caffelib.cc:1703] Net total flops=1582671872 / total params=6990272
I0427 09:22:41.974499  2778 caffelib.cc:103] Using GPU 1
INFO - 09:22:41 - Ignoring source layer loss3/loss3
ERROR - 09:22:42 - service pred_serv prediction call failed

ERROR - 09:22:42 - Thu Apr 27 09:22:42 2017 UTC - 127.0.0.1 "POST /predict" 500 1869


```

Here is the error I obtained from the predictions.
INPUT
```
print(predict_output)
```
OUTPUT
```
{'status': {'code': 500,
  'dd_code': 1007,
  'dd_msg': 'src/caffe/layers/cudnn_conv_layer.cu:28 / Check failed (custom): (status) == (CUDNN_STATUS_SUCCESS)',
  'msg': 'InternalError'}}
```

Now if I do the same experiment by hiding the first GPU so that only the second remains and is called GPU0 it works normally.

Moreover, I did a test directly on your fork of Caffe (https://github.com/beniz/caffe/commits/master) using the two GPUs and it works as well. Working well meaning be able to predict using PyCaffe with each of the two Gpus.

The error may come from how I created the service as suggests https://github.com/beniz/deepdetect/issues/224 but I could not find it.

Do you have any clue?

Thanks.

**Comment by YaYaB** [comment]
Hi,

Did you have time to take a look on this?

**Comment by beniz** [comment]
I haven't been able to replicate, I'll try again, just in case... especially if you have more info.

**Comment by beniz** [comment]
So, I believe your problem comes from CUDNN. You can check by rebuilding DD at last current commit (1f2d49041656fd0aabcd2d2db44bfc001bf6dbd5), that adds a bit more verbosity to prediction error on the server side. Then run a prediction on GPU 1, you should see a CUDNN error on the server side.

If that is the case, then you can test further as follows, from your `build` directory:

```
cd caffe_dd/src/caffe_dd
make clean
```
then edit `Makefile.config` and set `USE_CUDNN := 0`
```
make
cd ../../../
make
```
Try again on GPU 1 and my bet is that it should work. If that is the case, my guess is that your PyCaffe builds without CUDNN and thus works, while your DD build uses CUDNN and fails. Why it may fail is beyond my current understanding, and it does not seem to happen on all machines. 

CUDNN is a proprietary piece, try using v5 if you were using v6. Also check that you are not having multiple versions on your machine. Typically, TF pre-builds use v5 while some other software use v6.

**Comment by beniz** [comment]
Also, FTR, see https://groups.google.com/d/msg/caffe-users/DGlR5XL98r8/ggEXjX8HBwAJ

**Comment by YaYaB** [comment]
I have done the same tests using the last version of DD (commit : 1f2d49041656fd0aabcd2d2db44bfc001bf6dbd5).
I get the same error using GPU1, note that the GPU has enough memory to process the input:
```
E0531 09:33:22.140574 31437 caffelib.cc:1325] Error while proceeding with unsupervised prediction forward pass, not enough memory? src/caffe/layers/cudnn_conv_layer.cu:28 / Check failed (custom): (status) == (CUDNN_STATUS_SUCCESS)
INFO - 09:33:09 - Ignoring source layer loss3/loss3
ERROR - 09:33:22 - service pred_serv prediction call failed
ERROR - 09:33:22 - Wed May 31 09:33:22 2017 UTC - 127.0.0.1 "POST /predict" 500 15322
```

Without CUDNN it works, this is what I used to do. However because I wanted to use CUDNN I found myself stuck with this issue. To verify this I tested with the last version of DD without CUDNN and it works.

About PyCaffe, I used a version built with CUDNN and it worked well using the two GPUs. On this side I have no issue, that makes me think that the issue might not be CUDNN.
Moreover when I try on a virtualenv displaying only one GPU with the latest CUDNN version DD works whatever GPU I am using.

So yes, not using CUDNN might be a solution but it's very strange that I can use it with Pycaffe and not with DD.
